const pins = [
  { name: 'pow3v3', type: 'ground' },
  { name: 'pow5v', type: 'power' },
  { name: 'gpio 2', type: 'io', value: null },
  { name: 'pow5v', type: 'power' },
  { name: 'gpio 3', type: 'io', value: null },
  { name: 'gnd', type: 'ground' },
  { name: 'gpio 4', type: 'io', value: null },
  { name: 'gpio 14', type: 'io', value: null },
  { name: 'gnd', type: 'ground' },
  { name: 'gpio 15', type: 'io', value: null },
  { name: 'gpio 17', type: 'io', value: null },
  { name: 'gpio 18', type: 'io', value: null },
  { name: 'gpio 27', type: 'io', value: null },
  { name: 'gnd', type: 'ground' },
  { name: 'gpio 22', type: 'io', value: null },
  { name: 'gpio 23', type: 'io', value: null },
  { name: 'pow3v3', type: 'power' },
  { name: 'gpio 24', type: 'io', value: null },
  { name: 'gpio 10', type: 'io', value: null },
  { name: 'gnd', type: 'io', value: null },
  { name: 'gpio 9', type: 'io', value: null },
  { name: 'gpio 25', type: 'io', value: null },
  { name: 'gpio 11', type: 'io', value: null },
  { name: 'gpio 8', type: 'io', value: null },
  { name: 'gnd', type: 'ground' },
  { name: 'gpio 7', type: 'io', value: null },
  { name: 'gpio 0', type: 'io', value: null },
  { name: 'gpio 1', type: 'io', value: null },
  { name: 'gpio 5', type: 'io', value: null },
  { name: 'gnd', type: 'ground' },
  { name: 'gpio 6', type: 'io', value: null },
  { name: 'gpio 12', type: 'io', value: null },
  { name: 'gpio 13', type: 'io' },
  { name: 'gnd', type: 'ground' },
  { name: 'gpio 19', type: 'io' },
  { name: 'gpio 16', type: 'io' },
  { name: 'gpio 26', type: 'io' },
  { name: 'gpio 20', type: 'io' },
  { name: 'gnd', type: 'ground' },
  { name: 'gpio 21', type: 'io' },
];

module.exports = pins;
